fixing syntax issues

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -28,50 +28,50 @@ jobs:
             docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
             docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-    deploy:
-      name: Deploy to EC2
-      runs-on: ubuntu-latest
-      needs: build
-      steps:
-          - name: Configure AWS ECR credentials
-            uses: aws-actions/configure-aws-credentials@v4
-            with:
-              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-              aws-region: ${{secrets.AWS_REGION}}
-          - name: Login to Amazon ECR
-            id: login-aws-ecr
-            uses: aws-actions/amazon-ecr-login@v2
-          - name: Echo
-            run: echo ${{ steps.login-aws-ecr.outputs.registry }}
-          - name: Deploy to EC2
-            run: | 
-              command_id=$(aws ssm send-command \
-              --document-name "AWS-RunShellScript" \
-              --parameters commands='[
-                "aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
-                "docker pull ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.AWS_ECR_REPO}}:latest",
-                "docker run --rm -d -p 3000:3000 --name api ${{steps.login-aws-ecr.outputs.registry}}/${{secrets.AWS_ECR_REPO}}:latest"]' 
-              --query "Command.CommandId" --output text \
-              --targets "Key=instanceids,Values=i-08e4d6d7fb7254d2e,i-0d1f4c573bbb563f0" \
-              --comment "Pull Docker Image and run it")
+  deploy:
+    name: Deploy to EC2
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+        - name: Configure AWS ECR credentials
+          uses: aws-actions/configure-aws-credentials@v4
+          with:
+            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            aws-region: ${{secrets.AWS_REGION}}
+        - name: Login to Amazon ECR
+          id: login-aws-ecr
+          uses: aws-actions/amazon-ecr-login@v2
+        - name: Echo
+          run: echo ${{ steps.login-aws-ecr.outputs.registry }}
+        - name: Deploy to EC2
+          run: | 
+            command_id=$(aws ssm send-command \
+            --document-name "AWS-RunShellScript" \
+            --parameters commands='[
+              "aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
+              "docker pull ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.AWS_ECR_REPO}}:latest",
+              "docker run --rm -d -p 3000:3000 --name api ${{steps.login-aws-ecr.outputs.registry}}/${{secrets.AWS_ECR_REPO}}:latest"]' 
+            --query "Command.CommandId" --output text \
+            --targets "Key=instanceids,Values=i-08e4d6d7fb7254d2e,i-0d1f4c573bbb563f0" \
+            --comment "Pull Docker Image and run it")
 
               echo "$command_id"
 
-              aws ssm wait command-executed \
-              --command-id $command_id \
-              --instance-id i-0d1f4c573bbb563f0 || true \
+            aws ssm wait command-executed \
+            --command-id $command_id \
+            --instance-id i-0d1f4c573bbb563f0 || true \
 
-              status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
+            status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
 
-              echo "$status"
+            echo "$status"
 
-              if [ "$status" == "Success" ]; then
-                echo "Command executed successfully"
-              else
-                echo "Command failed"
-                exit 1
-              fi
+            if [ "$status" == "Success" ]; then
+              echo "Command executed successfully"
+            else
+              echo "Command failed"
+              exit 1
+            fi
 
 
 
