added echo error and exit

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -66,6 +66,8 @@ jobs:
                 echo "Command executed successfully"
               else
                 echo "Command failed"
+                echo "Error: $status"
+                exit 1
               fi
 
 
